site_name: Tech Talks
site_author: Barbara Schiavinato
site_url: https://barbaraschiavinato.github.io/front-end-speeches/
use_directory_urls: false
not_in_nav: |
  /includes
nav:
  - 'Calendar': index.md
  - 'Q1 2025': 
    - 'Github Copilot': 'Q1-2025/github-copilot.md'
    - 'Real-time data': 
      - 'Introduction': 'Q1-2025/real-time-data/index.md'
      - 'Websockets': 'Q1-2025/real-time-data/websockets.md'
      - 'React SetUp': 'Q1-2025/real-time-data/react-setup.md'
      - 'Performance': 'Q1-2025/real-time-data/performance.md'
      - 'Alternatives': 'Q1-2025/real-time-data/alternatives.md'

extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
plugins:
  - search
  - git-authors:
      show_contribution: true
      sort_authors_by: contribution
      show_email_address: true
      exclude: 
        - include/
        - checklists/
        - tags.html
  - page-to-pdf:
      disableOnServe: true
      exclude: 
        - include/
        - tags.html
  - with-pdf:
      cover_title: Tech Talks
      cover_subtitle: Internal document
      cover_logo: img/logo-big.png
      author: Barbara Schiavinato
      copyright: © NTT DATA 2025
      debug_html: false
      toc_level: 3
      exclude_pages: 
        - tags.html
      output_path: tech-talk.pdf
markdown_extensions:
  - attr_list
  - neoteroi.timeline
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material 
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Noto Sans
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate

